### ISSUE TITLE
Maxmind::Request does not pass order_currency

### ISSUE THREAD

**Issue by jack-trikeapps** [adam12/maxmind#10]
Looks like a missing key in the optional_fields hash in Maxmind::Request.

**Comment by adam12** [comment]
You're right. Nice catch.

**Comment by jack-trikeapps** [comment]
You're welcome. Do you plan on cutting a release soon or should I just track master?

**Comment by adam12** [comment]
I will try to get one out Thursday.

Cheers.

**Comment by jack-trikeapps** [comment]
Great, thanks very much.

**Comment by adam12** [comment]
0.4.7 has just been cut.

Thanks again.

**Comment by jack-trikeapps** [comment]
You too. Thanks for being so quick.
